In [1]:
import numpy as np

In [2]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 

1.0


In [3]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

21


In [6]:
p , q , p+q

(array([[ 0],
        [10],
        [20]]),
 array([10, 11, 12]),
 array([[10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]]))

In [ ]:
arr = np.arange(0 , 20).reshape(5,4)
row = arr[1:4]


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.flip(row[: , -3:] , 0)

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])