In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]
np.array(l).reshape(2, -1)

array([[1, 2],
       [3, 4]])

In [4]:
x = np.array(l).reshape(1 , -1)
x , x.shape

(array([[1, 2, 3, 4]]), (1, 4))

In [5]:
np.where?

Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes


In [6]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
a.reshape(6,)

array([0, 1, 2, 3, 4, 5])

In [8]:
a.reshape(6,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])
rate = np.array([4.1, 3.8, 4.0, 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])


print("Votes (Array):", votes)
print("Costs (Array):", costs)
print("Ratings (Array):", rate)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]
Ratings (Array): [4.1 3.8 4.  2.6 1.1 3.5 4.7 2.5 2.8 3.4]


In [10]:
costs = np.char.replace(costs , "'" , "")
costs = costs.astype(float)
costs

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [11]:
np.set_printoptions(suppress = True , precision=2)

In [12]:
data = np.column_stack((rate , votes, costs))
data

array([[   4.1,  775. ,  800. ],
       [   3.8,  787. ,  800. ],
       [   4. ,  918. ,  800. ],
       [   2.6,   88. ,  300. ],
       [   1.1,  166. ,  600. ],
       [   3.5,  286. ,  600. ],
       [   4.7, 2556. ,  600. ],
       [   2.5,  324. ,  700. ],
       [   2.8,  504. ,  550. ],
       [   3.4,  402. ,  500. ]])

# sorting in numpy


#### np.sort(arr) -> returns the sorted array

#### np.argsort(arr) -> returns indices of the sorted array


In [13]:
np.sort(costs)

array([300., 500., 550., 600., 600., 600., 700., 800., 800., 800.])

In [14]:
np.argsort(costs)

array([3, 9, 8, 4, 5, 6, 7, 0, 1, 2])

### sorting in 2d array


In [15]:
np.sort(data, axis = 0) #sorts columns

array([[   1.1,   88. ,  300. ],
       [   2.5,  166. ,  500. ],
       [   2.6,  286. ,  550. ],
       [   2.8,  324. ,  600. ],
       [   3.4,  402. ,  600. ],
       [   3.5,  504. ,  600. ],
       [   3.8,  775. ,  700. ],
       [   4. ,  787. ,  800. ],
       [   4.1,  918. ,  800. ],
       [   4.7, 2556. ,  800. ]])

In [16]:
np.sort(data , axis = 1) #sorts rows

array([[   4.1,  775. ,  800. ],
       [   3.8,  787. ,  800. ],
       [   4. ,  800. ,  918. ],
       [   2.6,   88. ,  300. ],
       [   1.1,  166. ,  600. ],
       [   3.5,  286. ,  600. ],
       [   4.7,  600. , 2556. ],
       [   2.5,  324. ,  700. ],
       [   2.8,  504. ,  550. ],
       [   3.4,  402. ,  500. ]])

## vectorizing functions


In [17]:
def discouts(rating , costs):
    if(rating >= 4.0):
        return 0.9 * costs
    else:
        return costs
dvectorized = np.vectorize(discouts)
dvectorized(rate , costs)

array([720., 800., 720., 300., 600., 600., 540., 700., 550., 500.])

In [18]:
a  = np.arange(12).reshape(4, 3)
b = np.arange(3).reshape(3,)
c = np.arange(6).reshape(2, 3)
a ,b , c

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([0, 1, 2]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [19]:
a + b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

## Broadcasting


#### row broadcasting


In [20]:
a = np.arange(6).reshape(2, 3)
b = np.full(3, 100)
a , b

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([100, 100, 100]))

In [21]:
a + b

array([[100, 101, 102],
       [103, 104, 105]])

### col broadcasting


In [22]:
a = np.arange(20).reshape(5,4)
b = np.full(5, 100).reshape(5, 1)
print(f'{a=} , \n {b=} ,  \n {a + b=}')

a=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]]) , 
 b=array([[100],
       [100],
       [100],
       [100],
       [100]]) ,  
 a + b=array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119]])


### row and col broadcasting


In [23]:
a = np.arange(4).reshape(4, 1)
b = np.arange(5)
print(f"{a=} ,\n {b=} ,\n {a + b=}")

a=array([[0],
       [1],
       [2],
       [3]]) ,
 b=array([0, 1, 2, 3, 4]) ,
 a + b=array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])


In [24]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[10], [20], [30]])
print(f"{array1=} ,\n {array2=} ,\n {array1 + array2=}")
array1.shape , array2.shape

array1=array([[1, 2, 3]]) ,
 array2=array([[10],
       [20],
       [30]]) ,
 array1 + array2=array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])


((1, 3), (3, 1))

In [25]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
np.tile(a , [4,4])

array([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [28]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
a.sum(0) , a.sum(1)

(array([60, 66, 72, 78]), array([ 6, 22, 38, 54, 70, 86]))

In [39]:
np.split(a , 2) , np.vsplit(a , 2) , np.hsplit(a , 2)

([array([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
  array([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]])],
 [array([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
  array([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]])],
 [array([[ 0,  1],
         [ 4,  5],
         [ 8,  9],
         [12, 13],
         [16, 17],
         [20, 21]]),
  array([[ 2,  3],
         [ 6,  7],
         [10, 11],
         [14, 15],
         [18, 19],
         [22, 23]])])

In [37]:
np.split(a , [2 , 4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [40]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [41]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [42]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [45]:
np.hstack((arr , arr[:,[0]]))

array([[1, 2, 3, 1],
       [4, 5, 6, 4],
       [7, 8, 9, 7]])

In [48]:
arr[:,0].shape , arr[:,[0]].shape

((3,), (3, 1))

In [49]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [50]:
sorted_age = np.argsort(age)
sorted_age

array([3, 7, 4, 2, 6, 5, 0, 8, 1, 9])

In [54]:
np.array(birds)[sorted_age]

array(['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes',
       'spoonbills', 'Cranes', 'plovers', 'spoonbills'], dtype='<U10')

In [55]:
np.where(np.array(age) > 4.0 , 1 , -1)

array([ 1,  1, -1, -1, -1, -1, -1, -1,  1,  1])

In [57]:
arr[:,[0]]

array([[1],
       [4],
       [7]])

In [59]:
arr = np.array([[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]])
arr.shape

(2, 3, 3)

In [60]:
arr[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [61]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [84]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr

array([[ 2,  3,  4,  5],
       [ 1,  7,  3,  5],
       [ 2,  8,  6,  9],
       [11, 23, 12, 19]])

In [85]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [86]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [87]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [88]:
arr, arr.shape

(array([[ 2,  3,  4,  5],
        [ 1,  7,  3,  5],
        [ 2,  8,  6,  9],
        [11, 23, 12, 19]]),
 (4, 4))

In [89]:
def fn(arr):
    temp = np.zeros((arr.shape[0]+2, arr.shape[1]+2))
    print(temp.shape)
    temp[1:-1 , 1:-1] = arr
    return temp
fn(arr)

(6, 6)


array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  3.,  4.,  5.,  0.],
       [ 0.,  1.,  7.,  3.,  5.,  0.],
       [ 0.,  2.,  8.,  6.,  9.,  0.],
       [ 0., 11., 23., 12., 19.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [90]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])
data

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [114]:
def fn(data , nsplits = 0):
    splits = np.vsplit(data , nsplits)
    # print(np.array(splits)[:-1])
    x = np.array(splits[-1])
    y = np.array(splits[:-1]).reshape(-1 , x.shape[1])
    print(x.shape , y.shape)
    temp = np.vstack((x, y))
    return temp
print(data)
fn(data , 4)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
(1, 3) (3, 3)


array([[100, 110, 120],
       [ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90]])

### Given a array of bird names and another array with corresponding ages of the birds, find the name of the oldest bird in the list.


In [135]:
birds = ['parrot', 'owl', 'macaw', 'macaw', 'owl', 'owl', 'macaw', 'macaw', 'sparrow', 'owl', 'sparrow', 'parrot', 'macaw', 'peacock', 'sparrow', 'macaw', 'peacock', 'owl', 'owl', 'parrot']
ages = [8, 1, 12, 13, 13, 8, 11, 7, 6, 1, 7, 4, 12, 6, 1, 8, 14, 13, 14, 1]

In [133]:
birds = ['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock']  
ages = [6, 1, 6, 5, 7, 6, 0, 9, 0, 7]

In [132]:
def fn(birds , ages):
    max_age = np.argmax(ages)
    birds = np.array(birds)
    ages = np.array(ages)
    return birds[np.where(ages == np.max(ages))][0]

In [136]:
fn(birds , ages)

'peacock'